### ISSUE TITLE
docker-minecraft-server bug or fail

### ISSUE THREAD

**Issue by Goten87** [henkelmax/simple-voice-chat#385]
im trying to use the mod with https://github.com/itzg/docker-minecraft-server
and i cannot connect to the server i have opened the port on the container but it will not connect
keep getting this massage on client ```[VoiceChatAuthenticationThread/INFO]: Trying to authenticate voice connection```
can you help me in testing it as well or tell me what to do

sorry did not know where to posted this

**Comment by henkelmax** [comment]
Please visit the discord if you need help

**Comment by oOHiyoriOo** [comment]
Hi, just stumbled upon this and wanted to mention the solution: 
You probably just opened the port in your compose or dockerfile, but SimpleVoicechat needs a UDP port, 
default is TCP. 
In a compose you can fix it as following: 
```
services:
  minecraft-server:
    image: itzg/minecraft-server
    ports:
      - 27420:25565
      - 27421:27421/UDP
```
With 27421 being my Voice chat port.
I think with Dockerfile it's the same :D.
