### ISSUE TITLE
Port is unreachable despite forwarding correctly

### ISSUE THREAD

**Issue by dlmw** [henkelmax/simple-voice-chat#775]
### Confirmation

- [x] I have read the wiki

### Bug description

When I connect using my server's local address (`192.168.1.xxx`), Simple Voice Chat seems to work fine. When I connect using the public address, I cannot connect to Simple Voice Chat.

### Minecraft version

1.20.1

### Mod/Plugin version

1.20.1-2.5.26

### Mod/Plugin loader and version

Fabric Loader 0.16.9

### Steps to reproduce

Here's my Docker Swarm file:
```yml
services:
  minecraft:
    image: itzg/minecraft-server:java21
    deploy:
      placement:
        constraints:
          - "node.labels.minecraft==true"
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
      - "24454:24454/udp"
    environment:
      EULA: "TRUE"
      VERSION: "1.20.1"
      MEMORY: "3G"
      TYPE: "AUTO_CURSEFORGE"
      DATAPACKS: "/downloads/BCA-Datapack_1.0.2.zip,/downloads/CobbleTownsv1.0.2.zip,/downloads/PokéCostume[2.0].zip"
      CF_MODPACK_ZIP: "/downloads/Cobblemon- Star Academy-0.1.5.2.1.zip"
      CF_API_KEY: "[REDACTED]"
      CF_SLUG: cobblemon-star-academy
    volumes:
      - minecraft-data:/data
      - ./downloads:/downloads
    networks:
      - minecraft-network
    healthcheck:
      test: mc-health
      start_period: 2m
      interval: 5s
      retries: 20

volumes:
  minecraft-data:

networks:
  minecraft-network:
```

When I connect to my Minecraft server using its LAN address (`192.168.1.xxx`), I can connect just fine to the voice chat. However, when I use its public IP address, I can connect fine to the server in itself but not the voice chat. Port check tools also say that the "port is closed".

I'm guessing I need to fiddle around with `bind_address` - which I tried to set to "*" - or `voice_host`, but I would gladly use some help here.

### Log files

https://mclo.gs/G9cmb5n
